# Build the server, test, and upload quality metrics to Sonar Cloud and CodeCov.
# Uses Java 17, the current Long Term Supported version of Java.

name: Build, test, and qulity

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        # Disabling shallow clone is used by Sonar
        fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '22'
        distribution: 'adopt'
    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      #Change to default builder once we can build with Java 17
      run: ./gradlew build jacocoTestReport koverXmlReport jibBuildTar --info
    - name: Sonar
      if: ${{ github.actor != 'dependabot[bot]' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GRADLE_OPTS: -XX:MaxMetaspaceSize=700m
      run: |
        ./gradlew --stop
        ./gradlew sonarqube --info
    - name: CodeCov
      uses: codecov/codecov-action@v5
      with:
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
