# Try building the project with Java 18, the newest version of Java.

name: Build on newest Java

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 22
      uses: actions/setup-java@v5
      with:
        java-version: '22'
        distribution: 'zulu'
        check-latest: true
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build jacocoTestReport koverXmlReport --info
    - uses: codecov/codecov-action@v5
      with:
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
